---
discard_articles_older_than: 3
instant:
  - printout
  #- jekyll
  #- twitter
summary:
  - printout
  #- mailjet

omit_digest_on_weekdays:
  - Sunday

random_ps:
#- This is a random message

db_path: '../'
#db_path: '/home/user/db'  # Use this for Docker

twitter_api_key:
twitter_api_secret_key:
twitter_access_token:
twitter_access_token_secret:

github_user:
github_password:
github_repo:

mailjet_api_key:
mailjet_secret_key:
sent_to_mailjet_contact_list:
mailjet_contact_list_id:

email_recipients:
#  - john.doe@example.com
email_sender: # "jane.doe@example.com"
email_sender_name: # "Jane Doe"
email_footer: "Imprint:\nYour Name | Your street | Your Email address"